#### general settings
name: refusion
use_tb_logger: true
model: denoising
distortion: sr
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    optimizer: AdamW # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: ../dataset/DIV2K/DIV2K_train_HR
    dataroot_LQ: ../dataset/DIV2K/DIV2K_train_LR_bicubic/X4

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 32
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: ../dataset/DIV2K/DIV2K_valid_HR
    dataroot_LQ: ../dataset/DIV2K/DIV2K_valid_LR_bicubic/X4


#### network structures
# network_G:
#   which_model_G: ConditionalNAFNet
#   setting:
#     width: 64
#     enc_blk_nums: [1, 1, 1, 28]
#     middle_blk_num: 1
#     dec_blk_nums: [1, 1, 1, 1]

network_G:
  type: ConditionalUNet
  setting:
    in_nc: 8
    out_nc: 3
    nf: 64
    depth: 4

network_L:
  which_model: UNet
  setting:
    in_ch: 3
    out_ch: 3
    ch: 8
    ch_mult: [4, 8, 8, 16]
    embed_dim: 8

#### path
path:
  pretrain_model_G: ~
  pretrain_model_L: exp/unet_latent/latent_sr_250129-140132/models/latest_G.pth
  strict_load: true
  resume_state: ~
  root_exp: "./"

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion # Adam, AdamW, Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 50000
  warmup_iter: -1  # no warm up
  lr_steps: [20000, 35000, 450000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  tofile: true
  screen: true
