#### general settings
name: latent_sr
use_tb_logger: true
model: latent
distortion: sr
gpu_ids: [0]

degradation: # for some synthetic dataset that only have GTs
  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: ../dataset/DIV2K_sub/DIV2K_train_HR
    dataroot_LQ: ../dataset/DIV2K_sub/DIV2K_train_LR_bicubic/X4

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 32
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: ../dataset/DIV2K/DIV2K_valid_HR
    dataroot_LQ: ../dataset/DIV2K/DIV2K_valid_LR_bicubic/X4
    batch_size: 16
    GT_size: 512
    LR_size: 128


#### network structures
network_G:
  which_model_G: UNet
  setting:
    in_ch: 3
    out_ch: 3
    ch: 8
    ch_mult: [4, 8, 8, 16]
    embed_dim: 8

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  root_exp: "./"

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion # Adam, AdamW, Lion
  lr_G: !!float 3e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 10000
  warmup_iter: -1  # no warm up
  lr_steps: [5000, 7500]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e3

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e3
  tofile: true
  screen: true
