#### general settings
name: edsr_ntire
use_tb_logger: true
model: pixel_model
distortion: sr
gpu_ids: [3]

degradation: 
  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    optimizer: Adam # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: ../dataset/LSDIR/LSDIR_train_HR
    dataroot_LQ: ../dataset/LSDIR/LSDIR_train_LR_X4

    use_shuffle: true
    n_workers: 16  # per GPU
    batch_size: 64
    GT_size: 192
    LR_size: 48
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    use_shuffle: false
    batch_size: 16
    GT_size: 512
    LR_size: 128
    color: RGB
    dataroot_GT: ../dataset/LSDIR/val1/HR/val
    dataroot_LQ: ../dataset/LSDIR/val1/X4/val


#### network structures
network_G:
  type: EDSR
  setting:
    n_resblocks: 32
    n_feats: 256
    rgb_range: 3
    n_colors: 3
    res_scale: 1


#### path
path:
  pretrain_model_G: exp/edsr/edsr_ntire/models/19000_G.pth
  strict_load: true
  resume_state: exp/edsr/edsr_ntire/training_state/19000.state
  root_exp: "./"

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 134000 # 100 epochs
  warmup_iter: -1  # no warm up
  lr_steps: [20000, 40000, 60000]
  lr_gamma: 0.5
  eta_min: !!float 1e-8
  wd_G: 0

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  tofile: true
  screen: true
