#### general settings
name: edsr
use_tb_logger: true
model: pixel_model
distortion: sr
gpu_ids: [1]

degradation: 
  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    optimizer: Adam # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: ../dataset/DF2K/DF2K_train_HR
    dataroot_LQ: ../dataset/DF2K/DF2K_train_LR_bicubic/X4

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    GT_size: 128
    LR_size: 32
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    use_shuffle: false
    batch_size: 8
    GT_size: 512
    LR_size: 128
    color: RGB
    dataroot_GT: ../dataset/DF2K/DF2K_valid_HR
    dataroot_LQ: ../dataset/DF2K/DF2K_valid_LR_bicubic/X4


#### network structures
network_G:
  type: EDSR
  setting:
    n_resblocks: 16
    n_feats: 64
    rgb_range: 3
    n_colors: 3
    res_scale: 1


#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  root_exp: "./"

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 70000
  warmup_iter: -1  # no warm up
  lr_steps: [40000, 50000, 60000]
  lr_gamma: 0.5
  eta_min: !!float 1e-8
  wd_G: 0

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e4

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  tofile: true
  screen: true
